import * as esbuild from "esbuild";

await esbuild.build({
  entryPoints: ["api/boot.ts"],
  bundle: true,
  format: "esm",
  outdir: "dist",
  // Use "browser" platform to avoid injecting createRequire shim.
  // Node built-ins will be resolved via the external list + nodejs_compat flag.
  platform: "browser",
  // Resolve ESM entry points where available
  mainFields: ["module", "main"],
  conditions: ["worker", "import", "module"],
  // Mark all Node built-ins as external — Workers resolves them at runtime
  // via the nodejs_compat compatibility flag.
  external: [
    "node:buffer",
    "node:crypto",
    "node:events",
    "node:net",
    "node:stream",
    "node:tls",
    "node:url",
    "node:util",
    "node:zlib",
    "node:timers",
    "node:process",
    "node:string_decoder",
    "node:child_process",
    "node:dns",
    "node:http",
    "node:https",
    "node:os",
    "node:path",
    "node:fs",
    "node:module",
    "buffer",
    "crypto",
    "events",
    "net",
    "stream",
    "tls",
    "url",
    "util",
    "zlib",
    "timers",
    "process",
    "string_decoder",
    "child_process",
    "dns",
    "http",
    "https",
    "os",
    "path",
    "fs",
    "module",
  ],
  // Inject a minimal polyfill so __require calls in bundled CJS work
  banner: {
    js: [
      // Workers with nodejs_compat can import node: prefixed builtins.
      // This shim lets esbuild's CJS __require() wrapper resolve them.
      `import __buffer from 'node:buffer';`,
      `import __crypto from 'node:crypto';`,
      `import __events from 'node:events';`,
      `import __net from 'node:net';`,
      `import __stream from 'node:stream';`,
      `import __tls from 'node:tls';`,
      `import __url from 'node:url';`,
      `import __util from 'node:util';`,
      `import __zlib from 'node:zlib';`,
      `import __timers from 'node:timers';`,
      `import __process from 'node:process';`,
      `import __string_decoder from 'node:string_decoder';`,
      `var __node_modules = {`,
      `  'node:buffer': __buffer, 'buffer': __buffer,`,
      `  'node:crypto': __crypto, 'crypto': __crypto,`,
      `  'node:events': __events, 'events': __events,`,
      `  'node:net': __net, 'net': __net,`,
      `  'node:stream': __stream, 'stream': __stream,`,
      `  'node:tls': __tls, 'tls': __tls,`,
      `  'node:url': __url, 'url': __url,`,
      `  'node:util': __util, 'util': __util,`,
      `  'node:zlib': __zlib, 'zlib': __zlib,`,
      `  'node:timers': __timers, 'timers': __timers,`,
      `  'node:process': __process, 'process': __process,`,
      `  'node:string_decoder': __string_decoder, 'string_decoder': __string_decoder,`,
      `};`,
      `globalThis.require = globalThis.require || function(id) {`,
      `  var m = __node_modules[id];`,
      `  if (m) return m;`,
      `  throw new Error('Cannot require "' + id + '"');`,
      `};`,
    ].join("\n"),
  },
});
